---
dist: trusty
sudo: false

language: go
go:
  - 1.10.x
  - master

cache:
  directories: [vendor/]

install: make
script: make test

notifications:
  email:
    on_success: never
    on_failure: never
